baseURL = "https://www.oldworlddata.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Old World Data"
theme = "oldworlddata"
author = "Johannes Friedl"

# Pagination
paginate = 3
paginatePath = "page"

# [taxonomies]
#   tag = "tags"
#   category = "categories"

# # Languages
# [languages.de]
#   languageName = "Deutsch"

#   [[languages.de.menu.main]]
#     url = "/post/"
#     name = "Artikel"
#     weight = 1
#   [[languages.de.menu.main]]
#     url = "/publication/"
#     name = "Publikationen"
#     weight = 2
#   [[languages.de.menu.main]]
#     url = "/about/"
#     name = "Über uns"
#     weight = 3

# [languages.en]
#   languageName = "English"

#   # Replace the default footer message with a localized message
#   # copyright = "Hugo template made with ❤ by Xzya"

#   [[languages.en.menu.main]]
#     url = "/post/"
#     name = "Articles"
#     weight = 1
#   [[languages.en.menu.main]]
#     url = "/publication/"
#     name = "Publications"
#     weight = 2
#   [[languages.en.menu.main]]
#     url = "/about/"
#     name = "About"
#     weight = 3

# # Links format
# [permalinks]
#   post = "/:year/:month/:title/"
#   blog  = "blog/:slug/"

[[menu.main]]
name                   = "Posts"
title                  = "Posts"
weight                 = 1
identifier             = "post"
url                    = "/post/"

[[menu.main]]
name                   = "About"
title                  = "About"
weight                 = 4
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Publications"
title                  = "Publication section"
weight                 = 2
identifier             = "publication"
url                    = "/publication/"

[[menu.main]]
name                   = "Data"
title                  = "Data section"
weight                 = 3
identifier             = "data"
url                    = "/data/"

[[params]]
showTagCloud = true
showScrollToTop = true
